icubam/www/handlers/db.py
This adds the ability to specify a csv export on the /db/ endpoint.
=> Added CSV export.

icubam/db/sqlite.py, icubam/www/handlers/show.py, icubam/www/handlers/update.py, icubam/www/templates/base.html, icubam/www/templates/index.html, icubam/www/templates/update_form.html
indentation + ajout des menus
Pour ce qui est de l'indentation, comme ce n'est pas standard, le mieux serait de partager le fichier de formatage à tout le monde (Pycharm: Preferences/Editor/Code style -> export to json)
=> indentation + add menus

icubam/www/static/style.css, icubam/www/templates/popup.html, icubam/www/templates/update_form.html, icubam/www/translations/fr.csv
- (*) equiped with artificial respirator
- submit / cancel ordering
- icu name aligned left
=> frontend small fixes

icubam/db/sqlite.py, icubam/db/test_sqlite.py, requirements.txt
We are still using SQLite do I kept the class the same. We can later change it.
=> Migrated sqlite3 to sqlalchemy.

.github/workflows/build-events.yml
=> basic auth for webhook

icubam/messaging/scheduler.py, icubam/messaging/server.py
=> fixing sms server

icubam/db/store.py, icubam/db/test_store.py
There are a few things to finish, e.g. auth by token, but you can review the current methods.
=> Initial version of data store.

icubam/db/store.py, scripts/populate_store_fake.py
The data is same as the fake db. Also removed the unique email constraint for now (to help with migration).
=> Added a script to populate fake store.

icubam/backoffice/handlers/base.py, icubam/backoffice/handlers/login.py, icubam/backoffice/templates/login.html, icubam/backoffice/translations/fr.csv
- mainly style
- simplifying backend (IMO)
=> Improving login page

.github/workflows/db-wipe-smoketest.yml, scripts/wipe_sensitive_info_db.py
This is an attempt to bring the wipe script up-to-date with current schema changes.
Marked as WIP because
- I don't know if it would make more sense to rewrite it using sqlalchemy?
- Needs comments on whether the wiping is correct / sufficient
- Needs basic automated testing at least (how? comments welcome... Should I run it on the results of populate_fake_db in CI?)
=> update wipe script to match db schema

.github/workflows/pythontest-linux.yml, dev_install.md, scripts/get_id_url.py, scripts/populate_db.py, scripts/populate_db_fake.py
* Update dev install procedure
* Use `click` to accept to populate_db
* Use flags for `.env` file in populate_db_fake
* A new script to get id url - cf. http://localhost:8888/update?id=<A_VERY_LONG_ID>
=> Update dev install procedure

icubam/backoffice/handlers/base.py, icubam/backoffice/handlers/icus.py, icubam/backoffice/handlers/users.py, icubam/backoffice/static/user.js, icubam/backoffice/templates/icu.html, icubam/backoffice/templates/user.html, icubam/backoffice/translations/fr.csv, icubam/base_server.py, icubam/db/store.py
since managed_icus / admin / password was not properly defined
=> Improve user edition in BO

icubam/config_test.py, resources/test.toml
This makes unit tests hermetic (for DB).
=> Replaced the test database with an in-memory one.

icubam/backoffice/handlers/base.py, icubam/backoffice/handlers/dashboard.py, icubam/backoffice/handlers/icus.py, icubam/backoffice/handlers/login.py, icubam/backoffice/handlers/logout.py, icubam/backoffice/handlers/messages.py, icubam/backoffice/handlers/operational_dashboard.py, icubam/backoffice/handlers/regions.py, icubam/backoffice/handlers/tokens.py, icubam/backoffice/handlers/users.py, icubam/backoffice/server.py, icubam/backoffice/server_test.py, icubam/backoffice/templates/base.html, icubam/backoffice/templates/home.html, icubam/backoffice/templates/icu.html, icubam/backoffice/templates/login.html, icubam/backoffice/templates/region.html, icubam/backoffice/templates/token.html, icubam/backoffice/templates/user.html, icubam/base_server.py, resources/config.toml, resources/test.toml
The idea is to prefix every root with /admin/ for instance. This PR support any prefix route.
=> root prefix in backoffice

icubam/backoffice/handlers/dashboard.py, icubam/backoffice/handlers/icus.py, icubam/backoffice/handlers/messages.py, icubam/backoffice/handlers/regions.py, icubam/backoffice/handlers/users.py, icubam/backoffice/templates/list.html, icubam/messaging/sms_sender.py
Put more relevant content in ICUs, Users, etc.
=> better individual lists

icubam/backoffice/handlers/icus.py, icubam/backoffice/server.py, icubam/backoffice/templates/icu.html, icubam/db/store.py, icubam/messaging/server.py, icubam/www/server.py
- with the backoffice, no need to have those url printed at start anymore.
- there was a bug with the active button on icu page
=> fixing icu page bug + removing all urls from start logs

docker/docker-compose-core.yml, docker/docker-compose.yml
Use env variable to set image name and tag in docker compose
=> Add support for env provided image name and tag

icubam/backoffice/handlers/users.py, icubam/db/store.py
It is a fix with a TODO since i believe a good query should fix the problem
=> fixing user save in manager mode

docker/README.md, docker/docker-compose-core.yml, docker/docker-compose.yml, docker/scripts/docker_run.sh, docker/scripts/docker_run_bo.sh
Uses env variables for DB/toml locations with defaults as usual
Removes references to pickle token
=> Allows to setup alternative locations for DBs and config file in docker

icubam/backoffice/server.py, icubam/backoffice/templates/map.html, icubam/map_builder.py, icubam/www/handlers/upload_csv.py
=> fixing static routes

.github/workflows/docker-build-run.yml, docker/docker-compose.yml
Fix missing port definition in one of the compose file
=> Docker fix

icubam/backoffice/handlers/home.py, icubam/icu_tree.py, icubam/icu_tree_test.py, icubam/map_builder.py
This PR also solves the problem of 0 lat/longs
=> improve map speed + removing zero counts from map

.github/workflows/docker-build-run.yml, docker/configs/nginx/app.conf, docker/configs/nginx/app.conf.dev, docker/configs/nginx/app.conf.prod
Nginx was redirecting front/bo calls to the same container.
=> Fix redirect to proper container

icubam/backoffice/handlers/base.py, icubam/backoffice/handlers/tokens.py, icubam/backoffice/templates/token.html, icubam/db/store.py, icubam/db/test_store.py, icubam/www/handlers/base.py, icubam/www/handlers/db.py, icubam/www/handlers/home.py, icubam/www/handlers/upload_csv.py
This PR introduces a new column in the exernal_clients table.
=> Tokens with regions and access type

.pre-commit-config.yaml, doc/install.md, requirements-dev.txt
Add a yapf pre-commit hook for convenience, plus setup instructions.
=> add yapf pre-commit hook

.github/workflows/docker-build-run.yml, .github/workflows/python-linters.yml, .github/workflows/shellcheck.yml, setup.py
Add check for minimal supported sqlite3 version in setup.py.
It the version is too low, things mostly work except for a few DB queries that return wrong results which is pretty bad. cf. https://github.com/icubam/icubam/pull/278#issuecomment-614182505
=> Add check for sqlite3 version in setup.py

.github/workflows/python-linters.yml
This seems like the low-hanging fruit of conda pruning :-)
=> remove conda from linter jobs in CI

icubam/db/synchronizer.py
=> Fixed problem with import on CSVs for ICUs.

scripts/csv_lookup_finess.py
This PR replaces #291 with an external script which preprocesses ICU CSV files before import. Based on the provided FINESS data, it automatically adds GPS coordinates and city information. It is useful e.g. when adding all ICUs from a new region.
=> Add script to preprocess ICUs CSV files based on FINESS data

conftest.py, icubam/backoffice/handlers/operational_dashboard.py, icubam/backoffice/templates/operational-dashboard-base.html, icubam/backoffice/templates/operational-dashboard.html, icubam/predicu/analytics_server.py, icubam/predicu/plot/__init__.py, icubam/predicu/plot/flux_dept_lits_dept_visu_4panels.py, icubam/predicu/tests/test_plot.py
Partially addresses https://github.com/icubam/icubam/issues/284
=> Working on integration of predicu plots into the dashboard

icubam/backoffice/static/map.css, icubam/backoffice/templates/map.html
=> fixing map in BO

icubam/backoffice/static/map.css, icubam/backoffice/templates/map.html, icubam/www/static/map.js, icubam/www/static/style.css, icubam/www/templates/popup.html
There were two css being called ...
=> Fixing map again! (CSS). Closes #345

.github/workflows/build-events.yml, .github/workflows/docker-build-run.yml, .github/workflows/docker-package.yml
This is a first step towards full CICD, as discussed [here](https://predicu-covid-19.slack.com/archives/C010YQFDZLL/p1586870546121700).
1. Merge relevant PRs in CD repository.
2. Set `GITLAB_PROJECT_URL` secret in this project. (I don't have access.)
3. Set `GITLAB_TRIGGER_TOKEN` secret in this project. (I don't have access.)
=> Continuously deliver to staging environment

icubam/icu_tree.py, icubam/icu_tree_test.py, icubam/map_builder.py, icubam/www/templates/popup.html, resources/config.toml
- add the possibility to show or not the empty icus
- consistent display for icu without phones
- cut the tree based on level + capacity
- move port of server to 8887 because 8888 is sometimes used by other stuffs
=> fixing map for paca

icubam/backoffice/handlers/base.py, icubam/backoffice/handlers/bedcounts.py, icubam/backoffice/handlers/icus.py, icubam/backoffice/handlers/messages.py, icubam/backoffice/handlers/regions.py, icubam/backoffice/handlers/tokens.py, icubam/backoffice/handlers/upload.py, icubam/backoffice/handlers/users.py, icubam/backoffice/server_test.py, icubam/backoffice/templates/list.html, icubam/db/synchronizer.py, icubam/db/test_synchronizer.py, resources/test/bedcounts.csv, scripts/csv_import.py
This PR makes it possible to import bedcounts CSV files.
Not sure how to handle selection of timezone. @dulacarnold any suggestions? I can probably get the browser timezone through JS, for example.
=> Bedcount import endpoint

icubam/db/wipe.py
Seems that there was a missing `commit()` in the wipe script. This wasn't found during tests so this PR  probably requires at least a regression test...
=> FIX commit changes in wipe script

doc/README.md, doc/authentication.md
This adds some documentation for the authentication and permission approaches currently used.
Partially addresses https://github.com/icubam/icubam/issues/271
Rendered version in https://github.com/rth/icubam/blob/doc-auth/doc/authentication.md
=> DOC Add authentication documentation

icubam/db/test_wipe.py, icubam/db/wipe.py
Follow-up to #393 
(I confirmed that if the session was not committed, the tests would fail)
=> TST update wipe unit tests

icubam/analytics/analytics_server.py, icubam/analytics/image_url_mapper.py, icubam/analytics/operational_dashboard.py, icubam/analytics/plots/__init__.py, icubam/analytics/plots/barplot_beds_per.py, icubam/analytics/plots/barplot_flow_per.py, icubam/analytics/plots/lineplot_beds_per.py, icubam/analytics/tests/test_image_url_mapper.py, icubam/analytics/tests/test_plot.py, icubam/backoffice/static/dist/css/dashboard.css, icubam/backoffice/templates/operational-dashboard.html, icubam/www/translations/es.csv, icubam/www/translations/fr.csv
Fixes rendering of new figures in the dashboard following refactoring in https://github.com/icubam/icubam/pull/389
=> Render latest png figures in the dashboard

icubam/analytics/plots/barplot_beds_per.py
Fix filtering of data to last 7 and 14 days in barplot_beds_per. This was mising in I think https://github.com/icubam/icubam/pull/404 
It also fixes aspect ratio of figures BTW
=> Fix 7D and 14D filtering in barplot_beds_per

.github/workflows/docker-package.yml
Leave github docker packages as it requires authentication even for public images.
=> Use docker hub and leave github docker packages

icubam/authenticator.py, icubam/backoffice/handlers/consent.py, icubam/backoffice/handlers/upload.py, icubam/sentry.py, icubam/www/token.py
Flake 8 CI currently would fail on master because the latest flake8 version adds a few new checks for f-strings. This fixes it.
Could someone please approve this PR, so it doesn't block CI in other PRs (e.g. https://github.com/icubam/icubam/pull/411)? Thanks!
=> Fix flake8 CI
