icubam/icubam

icubam/www/static/map.js
resources/config.toml

When the maps was all expanded and you clicked on one to remove it you have a map with N-1 objects. At this point, when toggling it would end up with 1 object on, instead of erasing them all, which is more natural.

fixing toggle

---

.github/workflows/pythontest-linux.yml
icubam/db/test_gsheets.py

Unit tests should pass from a "vanilla" clone without the need for tweaking / setting a configuration, and should not require secrets. Hence, this PR sets a dummy `JWT_TOKEN` env var for testing, disables `test_gsheets` as it requires a secret and enables github actions on pull requests to ease collaboration.

unit tests should pass on a vanilla clone

---

icubam/backoffice/handlers/list_users.py
icubam/backoffice/handlers/logout.py
icubam/backoffice/handlers/user.py
icubam/backoffice/server.py
icubam/backoffice/server_test.py
icubam/db/gsheets.py
icubam/db/queue_writer.py
icubam/db/sqlite.py
icubam/db/store.py
icubam/db/synchronizer.py
icubam/db/test_store.py
icubam/messaging/scheduler.py
icubam/messaging/server.py
icubam/time_utils.py
icubam/time_utils_test.py
icubam/www/handlers/db.py
icubam/www/handlers/home.py
icubam/www/handlers/show.py
icubam/www/handlers/update.py
icubam/www/handlers/upload_csv.py
icubam/www/updater.py

Removes unused imports. Obtained with,
```
flake8 --select=F401 icubam
```
As far as I can tell `from absl import logging` does have some side effects on import, so I left it there.

MAINT Remove unused imports

---

icubam/__init__.py
requirements.txt

A follow up fix on  https://github.com/icubam/icubam/pull/127 since `importlib.metadata` is not available in Python <=3.7 as detected by @olivierteboul 
This instead uses `pkg_resources` which is part of setuptools.
This adds `setuptools` to runtime dependencies (which is installed by pip by default regardless of dependencies anyway).
**Edit:** we only should merge this if we want to support Python <=3.7.

FIX Use pkg_resources for version determination in __init__

---

.github/workflows/build-events.yml

`.` is a litteral dot in the filter syntax. Fix release candidate dispatch filter.

Fix dispatch pattern

---

icubam/www/handlers/show.py

A new key `icu` appeared in the returned data dict. This key corresponds to a dict that contained not serializable data types such as DateTime. Leading to a server error that propagated to an Ajax error and not showing the dashboard's table.
Fixed this issue by just removing the corresponding key `icu` which did not any data used on the front end for now.

Hotfix for dashboard

---

icubam/backoffice/handlers/operational_dashboard.py
icubam/backoffice/server.py
icubam/backoffice/static/dist/css/dashboard.css
icubam/backoffice/templates/operational-dashboard.html
resources/config.toml
resources/test.toml

This adds an `extra_plots_dir` config parameter to `config.toml`. When it points to an existing dir, any png figure in that folder will be rendered at the end of `/operational-dashboard` page.
This is fully optional, if the `extra_plots_dir` is a non existing path or a folder with no `.png`, the previous behavour is unchanged.
TODO:
Will add a separate PR to re-generate these figures periodically.

Optionally render extra plots in the /operational-dashboard

---

.github/workflows/db-wipe-smoketest.yml
.github/workflows/docker-build-run.yml
.github/workflows/pythontest-linux.yml

Avoid redundant CI jobs when PRs are opened from upstream branches.
Makes CI trigger from either PRs to master or pushes to master (e.g. when the PR is merged).

Trigger CI on PRs or push in master

---

doc/docker.md

+ Remove trailing whitespaces for cleaner diffs.

Fix typo in doc/docker.md: $HOMR -> $HOME

---

docker/scripts/status.sh

Make it easier to quickly check the status of the `docker-compose` deployment.
This is useful for both developers and for CICD.
```console
$ shellcheck docker/scripts/status.sh
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.7.1
license: GNU General Public License, version 3
website: https://www.shellcheck.net
```
```console
$ ./docker/scripts/status.sh
Name                     Command                 State                       Ports
----------------------------------------------------------------------------------------------------------
icubam-bo-server    /bin/bash -c ./start_serve ...   Restarting
icubam-server       /bin/bash -c ./start_server.sh   Restarting
icubam-sms-server   /bin/bash -c ./start_serve ...   Restarting
icubam_certbot_1    /bin/sh -c trap …
```

Add script to check docker-compose's status

---

doc/install.md
icubam/config.py
scripts/csv_export.py
scripts/csv_import.py
scripts/generate_api_key.py
scripts/get_id_url.py
scripts/migrate_db.py
scripts/populate_db.py
scripts/populate_db_fake.py
scripts/run_server.py
scripts/schedule_sms.py
scripts/send_sms.py
scripts/synchronize_db.py
scripts/update_password.py

This PR follows suggestions made in https://github.com/icubam/icubam/pull/117#discussion_r401226576
As a side effect, it also makes instructions in `doc/install.md` succeed when they were previously failing to launch `run_server.py` because of a missing path to the `.env` file.

Refactor config paths

---

icubam/backoffice/handlers/base.py

IIUC, https://github.com/icubam/icubam/commit/fd464da6504be58302fa8d6132802088bacac807 is trying to extract column names from the first item in data passed to `render_list`, which fails if the data is empty.
I believe this fix should restore previous behavior on empty lists.
I haven't explored the testing infrastructure yet, so I'm not sure how to add a regression test. Any guidance welcome.
Fixes #251.

Fix #251: /list_tokens HTTP 500

---

icubam/backoffice/handlers/base.py
icubam/backoffice/handlers/bedcounts.py
icubam/backoffice/handlers/home.py
icubam/backoffice/handlers/icus.py
icubam/backoffice/handlers/messages.py
icubam/backoffice/handlers/operational_dashboard.py
icubam/backoffice/handlers/regions.py
icubam/backoffice/handlers/tokens.py
icubam/backoffice/handlers/users.py
icubam/backoffice/server_test.py
icubam/backoffice/templates/base.html
icubam/backoffice/templates/user.html

This PR:
- Makes backoffice tests detect when authentication fails for an endpoint. Previously, it was considered as a success because of a redirection to the login page.
- Fixes authentication from tests by using Tornado's `current_user` instead of rolling our own `user` field.
The second part especially needs careful review. We may want to do the same for `www`, but let's see how things work out here first.
TODO:
DO NOT SQUASH this PR, the history is clean and meaningful.

Fix endpoints tests

---

icubam/backoffice/handlers/base.py

CI is [currently failing](https://github.com/icubam/icubam/pull/249/checks?check_run_id=585221737#step:5:20) with:
```console
yapf -r --diff .
--- ./icubam/backoffice/handlers/base.py	(original)
+++ ./icubam/backoffice/handlers/base.py	(reformatted)
@@ -24,12 +24,7 @@
status = self.application.server_status
-    super().render(
-      path,
-      root=self.root_path,
-      server_status=status,
-      **kwargs
-    )
+    super().render(path, root=self.root_path, server_status=status, **kwargs)
def render_list(self, data, objtype, create_handler=None, **kwargs):
route = None if create_handler is None else create_handler.ROUTE
```
This PR applies the above change in order to please `yapf`, and have CI working again.

Please yapf: icubam/backoffice/handlers/base.py

---

.github/workflows/shellcheck.yml
.github/workflows/yapf.yml
docker/scripts/docker_run.sh
docker/scripts/docker_run_bo.sh
docker/scripts/docker_sms_run.sh
docker/scripts/init-letsencrypt.sh
docker/scripts/set_hostname_nginx.sh
docker/start_server.sh
docker/start_server_bo.sh
docker/start_server_sms.sh

To help find bugs early and enforce standards & best practices.
(Since `yapf` was added recently, I thought this would be one more step in that direction. Feel free to close if undesirable for whatever reason, though. 🙂)
- Lint shell scripts as part of CI.
- Fix all warnings raised by `shellcheck`:
```console
find . -type f -name '*.sh' | xargs spellcheck
```
- SC2086: https://github.com/koalaman/shellcheck/wiki/SC2086
- SC2215: https://github.com/koalaman/shellcheck/wiki/SC2215
- SC2162: https://github.com/koalaman/shellcheck/wiki/SC2162
- SC2128: https://github.com/koalaman/shellcheck/wiki/SC2128

Lint shell scripts as part of CI

---

icubam/backoffice/handlers/operational_dashboard.py
icubam/backoffice/server_test.py

Following https://github.com/icubam/icubam/pull/256 fixes  /operational-dashboard BO tests
Also helps for https://github.com/icubam/icubam/issues/197
Whether there should be data in get_visible_bed_counts_for_user is this test also a good question. Maybe we should run this test for admin and non admin user.  In any case not failing when the query returns no results cannot hurt.

TST Fix /operational-dashboard BO tests

---

.codecov.yml
.github/workflows/pythontest-linux.yml

Re-enable codecov to be a little less strict. In particular, no matter the coverage report it should not fail the CI and thus prevent merge.

Re-enable codecov

---

icubam/db/synchronizer.py
resources/test/icu.csv
resources/test/icu2.csv

This is a lighter version of #291, because @dulacarnold needs to quickly update FINESS numbers on the production server.
We only add parsing of the `legal_id` column in CSV files, without all the machinery for looking up FINESS data, that #291 does.

Take legal_id into account when importing from CSV

---

pyproject.toml

Sorry @dulacarnold I haven't realized what force_single_line=True does in isort (https://github.com/icubam/icubam/pull/315).
I don't find that,
```py
from typing import Dict, List, Optional
```
needs to be changed to,
```py
from typing import Dict
from typing import List
from typing import Optional
```
it's very verbose.

STY Revert isort force_single_line=True

---

.github/workflows/pythontest-linux.yml
.pre-commit-config.yaml
icubam/backoffice/handlers/base.py
icubam/backoffice/handlers/operational_dashboard.py
icubam/backoffice/handlers/tokens.py
icubam/backoffice/handlers/upload.py
icubam/backoffice/server.py
icubam/db/store.py
icubam/db/synchronizer.py
icubam/map_builder.py
icubam/messaging/handlers/schedule.py
icubam/predicu/data.py
icubam/predicu/plot/__init__.py
icubam/www/handlers/base.py
icubam/www/updater.py
requirements-dev.txt

I saw some code on master (probably now in prod) with typos in method names. I believe we really need something that catches such errors systematically before merge.
So this PR is fixing existing type errors on the code base and adding `mypy` to CI. The next step will be to add more type annotations, but the good thing is that it can be done incrementally.
Closes #180.

Fix type errors and add mypy check

---

icubam/backoffice/handlers/upload.py
icubam/db/synchronizer.py
icubam/db/test_synchronizer.py
resources/test/bedcounts.csv

The importer was calling `sync_users` instead of `sync_bedcounts`. We
also fix parsing of dates and add a test for this importer.

Fix CSV import of bedcounts and add test

---

.pre-commit-config.yaml

Following earlier discussion due to conflicts between yapf and isort.
Manual usage is still encouraged.

Disable isort pre-commit hook

---

.pre-commit-config.yaml
icubam/db/store.py
icubam/db/test_store.py

Re-opens https://github.com/icubam/icubam/issues/180
The fix in https://github.com/icubam/icubam/issues/180 was not sufficient as it also needs to account for `force=True`. For now just revert it.

FIX Disable the check of None user_id in get_visible_bed_counts_for_user

---

icubam/db/test_wipe.py
icubam/db/wipe.py
scripts/wipe_sensitive_info_db.py

This should have been two separate PRs but, oh well...
Rewrite the wipe script using SQLAlchemy to gain some future-proofing + add the option to reset admin username/password (may be useful on staging server)

Wipe using SQLAlchemy API + reset admin option

---

icubam/www/handlers/db.py
icubam/www/server_test.py

Closes https://github.com/icubam/icubam/issues/346
Also helps for API endpoint tests in https://github.com/icubam/icubam/issues/268
This is also very important so that changes in predicu don't break www service.

Fix /db/all_bedcounts?format=csv&preprocess=True + tests

---

.dockerignore
docker/Dockerfile

Solves #351 
Fix error in Action for docker image creation due to missing conftest.py.
The conftest.py file has been added in Dockerfile, which uses explicit copy of specific files and folders, and not a blanket copy of everything in the build folder except those in .dockerignore. 
While this prevents building a docker image with extra/unwanted files added in the local build folder (on test/dev machines) it also has the potential to create bugs if the Dockerfile has not been properly updated.
@rth @marccarre any recommendation for this ? (do blanket copy anyway as (1) on CICD, no risks or unwanted files in the image and (2) the images built on dev machines are just local anyway).

Fix missing config copy in Dockerfile

---

doc/cli.md
icubam/predicu/__main__.py
icubam/predicu/analytics_server.py
icubam/predicu/tests/test_export_data.py

Adds a script to manually generate plots for the dashboard https://github.com/icubam/icubam/issues/284 instead of the callback https://github.com/icubam/icubam/pull/222
There is some redundancy with `icubam.predicu.plot.__main__` but I thin we should move that one, one level up and expose it as `python -m icubam.predicu plot`, otherwise if each module has a script it's a bit hard to discover.

Plot generation script

---

icubam/predicu/plot/flux_dept_lits_dept_visu_4panels.py

The issue was that we are using the non default plot style (`seaborn-whitegrid`) which sets `frameon=False` for legends.

Fix plot legends in flux_dept_lits_dept_visu_4panels

---

doc/docker.md
doc/install.md
docker/build_fake_dbs.sh
docker/docker-compose-init-db.yml
docker/scripts/install_test_deployment.sh

Closes #381
**Why?**
Installing a basic instance of the platform for demonstration involves a number of step which are easy to get wrong. A simple, automated procedure is required in order to have people quickly play with the platform with a default database. 
**What?**
This PR adds a simple script that
-  creates the envvar file with default values (its content must be updated by the user and the install script launched again)
- download the relevant config and compose files from the github repository
- create resources folder, and generate the fake databae in it
- launches the app's containers (www, sms, back-office)
The app is then available using the url to access directly the back-office (http://localhost:8890/bo/) and the map (http://localhost:8888/) 
The script assumes docker and …

SImple script to automate demo deployment, documentation update

---

.codecov.yml
icubam/analytics/plots/__init__.py
icubam/analytics/preprocessing.py
icubam/analytics/tests/test_plot.py
icubam/analytics/tests/test_preprocessing.py

Re-adds some of the predicu tests for plots that didn't get included in https://github.com/icubam/icubam/pull/389
(otherwise plots are currently untested).
Also test the `spread_cum_jump` option in `preprocess_bedcounts`.

Re-add plot tests for analytics module

---

.github/workflows/terraform-check.yml
.gitignore
deploy/gcp/gce/README.md
deploy/gcp/gce/gce.tf
deploy/gcp/gce/init.sh
deploy/gcp/gce/outputs.tf
deploy/gcp/gce/variables.tf

Contains:
- Initialisation script (`gcloud` bootstrapping, etc.)
- Terraform template for:
- a `g1-small` VM
(for now, to limit credits consumption; it may need to be bigger to actually host ICUBAM)
- a public IP
- Documentation
- Lint Terraform templates via `terraform fmt -check`
Next steps:
- Add installation of ICUBAM itself

Add Terraform template to create VM under GCP

---

icubam/www/handlers/version.py

The /version endpoint is currently extremely slow (2s locally, 10s on prod server) because a query of all bedcounts is done as part of health checks (and that grows slower with more data).
Querying only latest bedcounts for each ICU is much faster (30ms locally). Assuming we still want to do some queries in this endpoint as opposed to just returning the version.

Faster /version endpoint

---

docker/docker-compose-proxy-nossl.yml

Add missing change in docker compose file (for nossl proxy setup) to mount the proper nginx conf file

Fix missing change for nginx conf filename in nossl compose

---

.github/doc-requirements.txt
README.md
doc/api.rst
doc/conf.py
doc/index.rst
doc/whats_new.md

A constraint with the API docs is that they are not updated automatically (e.g. with OpenAPI etc) and so have to be manually updated each time there is a change in handlers. Since we don't plan much changes in the future it should be OK I think.
**Edit:** rendered version in https://test-doc-icubam.readthedocs.io/en/web-api/api.html

Add Web API documentation and update release notes 
